config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get  'domain' => "dashboard#domain", as: :domain
  resources :domain_bookmarks
end

app/models/domain_bookmark.rb
class DomainBookmark < ActiveRecord::Base
  validates :domain, presence: true
  validates :domain, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :load_bookmark

  def load_bookmark
    @bookmarks = DomainBookmark.order("created_at DESC").limit(10)
    @bookmark_count = DomainBookmark.count
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  respond_to :js, :html

  def index
    @presenter = SearchPresenter.new params[:q]
  end

  def domain
    @presenter = DomainPresenter.new params[:domain]
  end
end

app/controllers/domain_bookmarks_controller.rb
class DomainBookmarksController < ApplicationController
  respond_to :js, :html

  def index
    @presenter = DomainBookmarkPresenter.new params[:q], params[:page]
  end

  def create
    domain_bookmark = DomainBookmark.new params_domain_bookmark
    if domain_bookmark.save
      flash[:notice] = "#{domain_bookmark.domain} is bookmarked"
    else
      render :nothing => true
      flash[:notice] = "Something wrong please try later" 
    end
  end

  def show
  end

  def edit
    @domain_bookmark = DomainBookmark.find params[:id]
  end

  def update
    domain = DomainBookmark.find params[:id]
    if domain.update_attributes params_edit_domain_bookmark
      redirect_to :back
      flash[:notice] = "Updated!"
    else
      redirect_to :back
      flash[:notice] = "Failed"
    end
  end

  def destroy
    domain = DomainBookmark.find params[:id]
    domain.destroy
    redirect_to :back
  end

  private

  def params_domain_bookmark
    params.require(:domain_bookmark).permit(:domain, :host, :subdomain, :path, :availability, :register_url)
  end

  def params_edit_domain_bookmark
    params.require(:domain_bookmark).permit(:price, :buy, :sell)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def register_link domain
    text = domain['availability'] == "available" ? "Buy Now" : "Make an offer"
    link = domain['register_url'] 
    #optional
    #domain['availability'] == "available" ? domain['register_url'] : UNDEVELOP_URL + "?q=#{domain['domain']}"
    link_to text, link, target: "_blank"
  end

  def register_button_link domain
    text = domain['availability'] == "available" ? "Buy Now" : "Make an offer"
    link = domain['availability'] == "available" ? domain['register_url'] : UNDEVELOP_URL + "?q=#{domain['domain']}"

    link_to text, link, target: "_blank", class: "btn btn-primary btn-lg"
  end

  def register_disable_button_link domain
    link_to domain['availability'].titleize , "#", class: "btn btn-info btn-lg disabled"
  end

  def check_info_link domain
    unless domain['availability'] == "available"
      link_to domain['domain'], domain_path + "?domain=#{domain['domain']}", remote: true
    else
      domain['domain']
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/domain_bookmarks_helper.rb
module DomainBookmarksHelper
end

app/views/dashboard/_bookmark.html.erb
<%= content_tag(:span, @bookmark_count, class: "bookmark") %>

app/views/dashboard/_bookmark_list.html.erb
<ul>
<% @bookmarks.each do |list| %>
  <li><%= check_info_link list %></li>
<% end %>
</ul>

app/views/dashboard/_content.html.erb
<div class="row">
  <div class="col-md-4">
    <h2>Search Domain</h2>
    <%= form_tag root_url, remote: true, method: :get do %>
      <div class="form-group">
        <%= label_tag "Domain Name" %>
        <%= text_field_tag :q, params[:q], placeholder: "Enter domain name", class: "form-control"%>
      </div>
      <%= submit_tag "Search", class: "btn btn-default" %>
    <% end %>

    <h3>My Bookmarks (<%= render "dashboard/bookmark" %>)</h3>
    <div class="bookmark_list"><%= render "dashboard/bookmark_list" %></div>
    <%= link_to "See all", domain_bookmarks_url, class: "btn btn-primary btn-lg btn-xs" %>
  </div>
  <div class="col-md-8">
    <p>
      <div id='results'></div>
    </p>
  </div>
</div>

app/views/dashboard/_domain.js.erb
<h2><%= @presenter.domain['query']%></h2>
<div class='highlight'>
  <%= register_disable_button_link @presenter.domain %>
  <%= register_button_link @presenter.domain %>

  <h3>Whois</h3>
  <p id="who_is"><%= @presenter.who_is.html_safe %></p>
  
  <h3>Purchase Options</h3>
  <ul>
  <% @presenter.domain['registrars'].each do |t| %>
    <li><%= link_to t['name'], t['register_url'], target: "_blank" %></li>
  <% end %>
  </ul>
</div>

app/views/dashboard/_result.js.erb
<% if  @presenter.domains.blank? %>
  <h2>Ops!!! something wrong</h2>
  <p>please fill out domain name field</p>
<% else %>
  <h2>Results for <%= @presenter.domains['query']%></h2>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Domain</th>
        <th>Host</th>
        <th>Sub Domain</th>
        <th>Path</th>
        <th>Available</th>
        <th>Register Info</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @presenter.domains['results'].each do |domain| %>
      <tr>
        <td><%= check_info_link domain %></th>
        <td><%= domain['host']%></td>
        <td><%= domain['subdomain']%></td>
        <td><%= domain['path']%></td>
        <td><%= domain['availability'].titleize %></td>
        <td><%= register_link domain %></td>
        <td><%= link_to "Bookmark", domain_bookmarks_url(domain_bookmark: domain), remote: true, method: :post, class: "btn btn-success btn-lg" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/dashboard/domain.html.erb
<%= render "content" %>

app/views/dashboard/domain.js.erb
$('#results').html('<%= escape_javascript render("dashboard/domain") %>');

app/views/dashboard/index.html.erb
<%= render "dashboard/content" %>

app/views/dashboard/index.js.erb
$('#results').html('<%= escape_javascript render("dashboard/result") %>');

app/views/domain_bookmarks/_list.html.erb
<h2>Domain Bookmark List</h2>
<table class="table table-condensed">
  <thead>
    <tr>
      <th><%= sort_link(presenter.search_domain, :domain) %></th>
      <th><%= sort_link(presenter.search_domain, :availability, "Available") %></th>
      <th>Register Info</th>
      <th><%= sort_link(presenter.search_domain, :price, "Price ($)") %></th>
      <th><%= sort_link(presenter.search_domain, :buy, "Buy ($)") %></th>
      <th><%= sort_link(presenter.search_domain, :sell, "Sell ($)") %></th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% presenter.domains.each do |domain| %>
    <tr>
      <td><%= domain.domain %></th>
      <td><%= domain.availability.titleize %></td>
      <td><%= register_link domain %></td>
      <td><%= domain.price || 'N/A' %></td>
      <td><%= domain.buy || 'N/A' %></td>
      <td><%= domain.sell || 'N/A' %></td>
      <td><%= link_to "edit", edit_domain_bookmark_url(domain), class: "btn btn-primary btn-lg btn-xs"%> | <%= link_to "delete", domain_bookmark_url(domain), class: "btn btn-danger btn-lg btn-xs", method: :delete, "data-confirm" => "Are you sure want to remove this domain?" %> </td>
    </tr>
    <% end %>
  </tbody>
</table>

<% if @presenter.present? %>
  <div class="col-xs-12 text-left">
    <%= paginate @presenter.domains %>
  </div>
<% end %>

app/views/domain_bookmarks/_search.html.erb
<h3>Filter</h3>
<div class='row'>
  <%= search_form_for @presenter.search_domain, class: "form-inline" do |f| %>
    <div class="form-group">
      <%= f.label :domain %>
      <%= f.search_field :domain_cont, class: "form-control" %>
      <%= f.submit "search", class: "btn btn-default" %>
      <%= link_to "Reset", domain_bookmarks_url, class: "btn btn-danger btn-lg btn-xs" %>
   </div>
    
  <% end %>
  
</div>

app/views/domain_bookmarks/create.js.erb
$('.bookmark').html('<%= escape_javascript render("dashboard/bookmark") %>');
$('.bookmark_list').html('<%= escape_javascript render("dashboard/bookmark_list") %>');

app/views/domain_bookmarks/edit.html.erb
<div class='row'>
  <h2> Edit <%= @domain_bookmark.domain %> </h2>
  <%= form_for @domain_bookmark, class: "form-inline" do |t| %>
    <div class="form-group">
      <%= t.label :price, "Price ($)" %>
      <%= t.text_field :price, class: "form-control" %>    
    </div>
    <div class="form-group">
      <%= t.label :buy, "Buy ($)" %>
      <%= t.text_field :buy, class: "form-control" %>  
    </div>
    <div class="form-group">
      <%= t.label :sell, "Sell ($)" %>
      <%= t.text_field :sell, class: "form-control" %>  
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  <% end %>
</div>

app/views/domain_bookmarks/index.html.erb
<div class='row'>
  <div class="col-md-12">
    <%= render "domain_bookmarks/search", presenter: @presenter %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render "domain_bookmarks/list", presenter: @presenter %>
  </div>
</div>

app/views/domain_bookmarks/show.html.erb
<h1>DomainBookmarks#show</h1>
<p>Find me in app/views/domain_bookmarks/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>Domain</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
      <%= link_to "&#8962; home".html_safe, root_url, class: "btn btn-default btn-lg btn-xs" %>
      <%= link_to "bookmarks", domain_bookmarks_url, class: "btn btn-warning btn-lg btn-xs" %>
      </div>
    </div>
    <%= yield %>    
  </div>
</body>
</html>